name: "publish to cloud"

on:
  push:
    branches:
      - gh-actions-playground

jobs:
  publish-cloud:
    permissions:
      contents: write
    strategy:
      fail-fast: false

    runs-on: macos-latest
    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.MTEST }}"
      - id: "upload-file"
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "src"
          destination: "testproject-c9c14.appspot.com/builds/public"
